
version: '3'

services:
  # MySQL service
  <MYSQL_SERVICE_NAME>:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: <MYSQL_ROOT_PWD>
      MYSQL_DATABASE: <MYSQL_DATABASE>
      MYSQL_USER: <MYSQL_USER>
      MYSQL_PASSWORD: <MYSQL_PASSWORD>
    ports:
      - "<MYSQL_PORT>:3306"

  # Node.js application service
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - <MYSQL_SERVICE_NAME>
    environment:
      DB_HOST: <MYSQL_SERVICE_NAME>
      DB_PORT: <MYSQL_PORT>
      DB_USER: <MYSQL_USER>
      DB_PASSWORD: <MYSQL_PASSWORD>
      DB_DATABASE: <MYSQL_DATABASE>
    ports:
      - "<HOST_APPLICATION_PORT>:<CONTAINER_APPLICATION_PORT>"
      - "<SIGNALLING_SERVER_PORT>:<CONTAINER_SIGNALLING_SERVER_PORT>"
      - "9229:9229"
