CREATE DATABASE IF NOT EXISTS <MYSQL_DATABASE> ;


-- Write the queries needed to create to the schema

-- Create users

CREATE USER IF NOT EXISTS '<MYSQL_USER>' @'%' IDENTIFIED BY '<MYSQL_PASSWORD>';
GRANT SELECT, INSERT, UPDATE, DELETE ON collab.* TO '<MYSQL_USER>'@'%';


-- Create Tables

CREATE TABLE IF NOT EXISTS <MYSQL_DATABASE>.<MYSQL_TABLE>
(
   id            INT(10) NOT NULL AUTO_INCREMENT,
   username      VARCHAR(255)
                   CHARACTER SET utf8mb4
                   COLLATE utf8mb4_0900_ai_ci
                   NOT NULL,
   secret        TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
   created_on    TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY(id),
   UNIQUE KEY username_unq(username)
)
ENGINE INNODB
COLLATE 'utf8mb4_0900_ai_ci'
ROW_FORMAT DEFAULT;

-- Create heltch check tables

-- Create the 'health_check' table
CREATE TABLE IF NOT EXISTS <MYSQL_DATABASE>.<MYSQL_HEALTH_TABLE> (
    id INT AUTO_INCREMENT PRIMARY KEY,
    value INT
);

-- Generate 5 rows of random data
INSERT INTO <MYSQL_DATABASE>.<MYSQL_HEALTH_TABLE> (value) VALUES (FLOOR(RAND() * 100));
INSERT INTO <MYSQL_DATABASE>.<MYSQL_HEALTH_TABLE> (value) VALUES (FLOOR(RAND() * 100));
INSERT INTO <MYSQL_DATABASE>.<MYSQL_HEALTH_TABLE> (value) VALUES (FLOOR(RAND() * 100));
INSERT INTO <MYSQL_DATABASE>.<MYSQL_HEALTH_TABLE> (value) VALUES (FLOOR(RAND() * 100));
INSERT INTO <MYSQL_DATABASE>.<MYSQL_HEALTH_TABLE> (value) VALUES (FLOOR(RAND() * 100));

